#!/usr/bin/env bash

if [ ! -d ".venv" ]; then
  python3 -m venv .venv
fi

if [ ! -f ".env" ]; then
  cp env.example .env
fi

mkdir -p db
sqlite3 "db/db" <db/init.sql

if [ ! -x src/main.py ]; then
  chmod +x src/main.py
fi

source .venv/bin/activate
pip install -r requirements.txt >/dev/null
python src/main.py
